// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RelationalDB))]
    partial class RelationalDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Definition.AttributeDomain.AttributeValue", b =>
                {
                    b.Property<string>("CharacteristicID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<float>("Max")
                        .HasColumnType("real");

                    b.Property<float>("Min")
                        .HasColumnType("real");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("CharacteristicID", "Type", "Level");

                    b.HasIndex("CharacteristicID", "Type", "Level")
                        .IsUnique();

                    b.ToTable("AttributeValues", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.AttributeDomain.Characteristic", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Characteristics", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.AttributeDomain.Effect", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Duration")
                        .HasColumnType("real");

                    b.Property<float?>("Interval")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Effects", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Entity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Entities", (string)null);

                    b.HasDiscriminator().HasValue("Entity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.EntityRelationship", b =>
                {
                    b.Property<string>("SourceEntityID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetEntityID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("SourceEntityID", "TargetEntityID", "Type");

                    b.HasIndex("TargetEntityID");

                    b.ToTable("EntityRelationships", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.Inventory", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlotCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.InventoryItem", b =>
                {
                    b.Property<string>("InventoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryID", "ItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.Item", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefaultAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Durability")
                        .HasColumnType("int");

                    b.Property<string>("EntityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stackable")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Category");

                    b.HasIndex("DefaultAction");

                    b.HasIndex("Type");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.ItemEffect", b =>
                {
                    b.Property<string>("ItemID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EffectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemID1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItemID", "EffectID");

                    b.HasIndex("EffectID");

                    b.HasIndex("ItemID1");

                    b.ToTable("ItemEffects", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.LocalizationDomain.Locale", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("Code");

                    b.HasIndex("IsEnabled");

                    b.ToTable("Locales", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.LocalizationDomain.LocalizationEntry", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Key");

                    b.HasIndex("LocaleCode");

                    b.HasIndex("Key", "LocaleCode")
                        .IsUnique();

                    b.ToTable("LocalizationEntries", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.Cell", b =>
                {
                    b.Property<string>("RoomID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.Property<string>("TileID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID", "X", "Y", "Z");

                    b.HasIndex("TileID");

                    b.HasIndex("RoomID", "X", "Y", "Z")
                        .IsUnique();

                    b.ToTable("Cells", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.EntitySpawnRule", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EntityID");

                    b.HasIndex("RoomID");

                    b.ToTable("EntitySpawnRules", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.Room", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.RoomConnection", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationEntityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationRoomID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceEntityID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceRoomID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("DestinationRoomID", "DestinationEntityID");

                    b.HasIndex("SourceRoomID", "SourceEntityID")
                        .IsUnique();

                    b.ToTable("RoomConnections", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.SpawnArea", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntitySpawnRuleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxX")
                        .HasColumnType("int");

                    b.Property<int>("MaxY")
                        .HasColumnType("int");

                    b.Property<int>("MinCount")
                        .HasColumnType("int");

                    b.Property<int>("MinX")
                        .HasColumnType("int");

                    b.Property<int>("MinY")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("EntitySpawnRuleID");

                    b.HasIndex("MaxX", "MaxY");

                    b.HasIndex("MinX", "MinY");

                    b.ToTable("SpawnAreas", (string)null);
                });

            modelBuilder.Entity("Domain.Other.IdentityDomain.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SteamID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SteamID")
                        .IsUnique()
                        .HasFilter("[SteamID] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Other.VersionDomain.DefinitionVersionLog", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("DefinitionVersions", (string)null);
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.AreaEffect", b =>
                {
                    b.HasBaseType("Domain.Definition.EntityDomain.Entity");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("AreaEffect");
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Creature", b =>
                {
                    b.HasBaseType("Domain.Definition.EntityDomain.Entity");

                    b.Property<string>("CharacteristicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InventoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasIndex("CharacteristicID");

                    b.HasIndex("InventoryID");

                    b.HasDiscriminator().HasValue("Creature");
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Portal", b =>
                {
                    b.HasBaseType("Domain.Definition.EntityDomain.Entity");

                    b.HasDiscriminator().HasValue("Portal");
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Projectile", b =>
                {
                    b.HasBaseType("Domain.Definition.EntityDomain.Entity");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<float>("Velocity")
                        .HasColumnType("real");

                    b.ToTable("Entities", t =>
                        {
                            t.Property("Duration")
                                .HasColumnName("Projectile_Duration");
                        });

                    b.HasDiscriminator().HasValue("Projectile");
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.WorldObject", b =>
                {
                    b.HasBaseType("Domain.Definition.EntityDomain.Entity");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInteractable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickupable")
                        .HasColumnType("bit");

                    b.ToTable("Entities", t =>
                        {
                            t.Property("InventoryID")
                                .HasColumnName("WorldObject_InventoryID");
                        });

                    b.HasDiscriminator().HasValue("WorldObject");
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Player", b =>
                {
                    b.HasBaseType("Domain.Definition.EntityDomain.Creature");

                    b.HasDiscriminator().HasValue("Player");
                });

            modelBuilder.Entity("Domain.Definition.AttributeDomain.AttributeValue", b =>
                {
                    b.HasOne("Domain.Definition.AttributeDomain.Characteristic", "Characteristic")
                        .WithMany("AttributeValues")
                        .HasForeignKey("CharacteristicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristic");
                });

            modelBuilder.Entity("Domain.Definition.AttributeDomain.Characteristic", b =>
                {
                    b.OwnsOne("Domain.Definition.LocalizationDomain.LocalizedText", "LocalizedText", b1 =>
                        {
                            b1.Property<string>("CharacteristicID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DescriptionKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NameKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CharacteristicID");

                            b1.ToTable("Characteristics");

                            b1.WithOwner()
                                .HasForeignKey("CharacteristicID");
                        });

                    b.Navigation("LocalizedText")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.AttributeDomain.Effect", b =>
                {
                    b.OwnsOne("Domain.Definition.LocalizationDomain.LocalizedText", "LocalizedText", b1 =>
                        {
                            b1.Property<string>("EffectID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DescriptionKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NameKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EffectID");

                            b1.ToTable("Effects");

                            b1.WithOwner()
                                .HasForeignKey("EffectID");
                        });

                    b.Navigation("LocalizedText")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Entity", b =>
                {
                    b.OwnsOne("Domain.Definition.EntityDomain.Component.Appearance", "Appearance", b1 =>
                        {
                            b1.Property<string>("EntityID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EyesID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HairID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PantID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShirtID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SkinID")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EntityID");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("EntityID");

                            b1.OwnsOne("Domain.Common.HSV", "HairColor", b2 =>
                                {
                                    b2.Property<string>("AppearanceEntityID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<float>("H")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.Property<float>("S")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.Property<float>("V")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.HasKey("AppearanceEntityID");

                                    b2.ToTable("Entities");

                                    b2.WithOwner()
                                        .HasForeignKey("AppearanceEntityID");
                                });

                            b1.OwnsOne("Domain.Common.HSV", "PantColor", b2 =>
                                {
                                    b2.Property<string>("AppearanceEntityID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<float>("H")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.Property<float>("S")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.Property<float>("V")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.HasKey("AppearanceEntityID");

                                    b2.ToTable("Entities");

                                    b2.WithOwner()
                                        .HasForeignKey("AppearanceEntityID");
                                });

                            b1.OwnsOne("Domain.Common.HSV", "SkinColor", b2 =>
                                {
                                    b2.Property<string>("AppearanceEntityID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<float>("H")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.Property<float>("S")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.Property<float>("V")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("real")
                                        .HasDefaultValue(0f);

                                    b2.HasKey("AppearanceEntityID");

                                    b2.ToTable("Entities");

                                    b2.WithOwner()
                                        .HasForeignKey("AppearanceEntityID");
                                });

                            b1.Navigation("HairColor");

                            b1.Navigation("PantColor");

                            b1.Navigation("SkinColor")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.Definition.EntityDomain.Component.Collision", "Collision", b1 =>
                        {
                            b1.Property<string>("EntityID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<float>("Height")
                                .HasColumnType("real");

                            b1.Property<bool>("IsBlocking")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsTrigger")
                                .HasColumnType("bit");

                            b1.Property<float>("Radius")
                                .HasColumnType("real");

                            b1.Property<string>("ShapeType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<float>("Width")
                                .HasColumnType("real");

                            b1.HasKey("EntityID");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("EntityID");
                        });

                    b.OwnsOne("Domain.Definition.LocalizationDomain.LocalizedText", "LocalizedText", b1 =>
                        {
                            b1.Property<string>("EntityID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DescriptionKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NameKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EntityID");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("EntityID");
                        });

                    b.Navigation("Appearance")
                        .IsRequired();

                    b.Navigation("Collision")
                        .IsRequired();

                    b.Navigation("LocalizedText")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.EntityRelationship", b =>
                {
                    b.HasOne("Domain.Definition.EntityDomain.Entity", null)
                        .WithMany()
                        .HasForeignKey("SourceEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Definition.EntityDomain.Entity", null)
                        .WithMany()
                        .HasForeignKey("TargetEntityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.Inventory", b =>
                {
                    b.OwnsOne("Domain.Definition.LocalizationDomain.LocalizedText", "LocalizedText", b1 =>
                        {
                            b1.Property<string>("InventoryID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DescriptionKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NameKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InventoryID");

                            b1.ToTable("Inventories");

                            b1.WithOwner()
                                .HasForeignKey("InventoryID");
                        });

                    b.Navigation("LocalizedText")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.InventoryItem", b =>
                {
                    b.HasOne("Domain.Definition.ItemDomain.Inventory", "Inventory")
                        .WithMany("DefaultItems")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Definition.ItemDomain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.Item", b =>
                {
                    b.OwnsOne("Domain.Definition.LocalizationDomain.LocalizedText", "LocalizedText", b1 =>
                        {
                            b1.Property<string>("ItemID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DescriptionKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NameKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemID");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemID");
                        });

                    b.Navigation("LocalizedText")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.ItemEffect", b =>
                {
                    b.HasOne("Domain.Definition.AttributeDomain.Effect", "Effect")
                        .WithMany()
                        .HasForeignKey("EffectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Definition.ItemDomain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Definition.ItemDomain.Item", null)
                        .WithMany("Effects")
                        .HasForeignKey("ItemID1");

                    b.Navigation("Effect");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Domain.Definition.LocalizationDomain.LocalizationEntry", b =>
                {
                    b.HasOne("Domain.Definition.LocalizationDomain.Locale", "Locale")
                        .WithMany("LocalizationEntries")
                        .HasForeignKey("LocaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.Cell", b =>
                {
                    b.HasOne("Domain.Definition.WorldDomain.Room", "Room")
                        .WithMany("Cells")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.EntitySpawnRule", b =>
                {
                    b.HasOne("Domain.Definition.EntityDomain.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Definition.WorldDomain.Room", "Room")
                        .WithMany("EntitySpawnRules")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.Room", b =>
                {
                    b.OwnsOne("Domain.Definition.LocalizationDomain.LocalizedText", "LocalizedText", b1 =>
                        {
                            b1.Property<string>("RoomID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("DescriptionKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NameKey")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RoomID");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomID");
                        });

                    b.Navigation("LocalizedText")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.RoomConnection", b =>
                {
                    b.HasOne("Domain.Definition.WorldDomain.Room", null)
                        .WithMany()
                        .HasForeignKey("DestinationRoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Definition.WorldDomain.Room", null)
                        .WithMany()
                        .HasForeignKey("SourceRoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.SpawnArea", b =>
                {
                    b.HasOne("Domain.Definition.WorldDomain.EntitySpawnRule", "EntitySpawnRule")
                        .WithMany("SpawnAreas")
                        .HasForeignKey("EntitySpawnRuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitySpawnRule");
                });

            modelBuilder.Entity("Domain.Definition.EntityDomain.Portal", b =>
                {
                    b.OwnsOne("Domain.Common.Vector2", "EntrancePosition", b1 =>
                        {
                            b1.Property<string>("PortalID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.HasKey("PortalID");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("PortalID");
                        });

                    b.OwnsOne("Domain.Definition.EntityDomain.Component.Collision", "Entrance", b1 =>
                        {
                            b1.Property<string>("PortalID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<float>("Height")
                                .HasColumnType("real");

                            b1.Property<bool>("IsBlocking")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsTrigger")
                                .HasColumnType("bit");

                            b1.Property<float>("Radius")
                                .HasColumnType("real");

                            b1.Property<string>("ShapeType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<float>("Width")
                                .HasColumnType("real");

                            b1.HasKey("PortalID");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("PortalID");
                        });

                    b.Navigation("Entrance")
                        .IsRequired();

                    b.Navigation("EntrancePosition")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Definition.AttributeDomain.Characteristic", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.Inventory", b =>
                {
                    b.Navigation("DefaultItems");
                });

            modelBuilder.Entity("Domain.Definition.ItemDomain.Item", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("Domain.Definition.LocalizationDomain.Locale", b =>
                {
                    b.Navigation("LocalizationEntries");
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.EntitySpawnRule", b =>
                {
                    b.Navigation("SpawnAreas");
                });

            modelBuilder.Entity("Domain.Definition.WorldDomain.Room", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("EntitySpawnRules");
                });
#pragma warning restore 612, 618
        }
    }
}
