FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY Contracts/Contract/Contract/Contract.csproj Contracts/Contract/Contract/

COPY GameService/API/API.csproj API/
COPY GameService/Application/Application.csproj Application/
COPY GameService/Domain/Domain.csproj Domain/
COPY GameService/Infrastructure/Infrastructure.csproj Infrastructure/

RUN dotnet restore API/API.csproj

COPY . .

WORKDIR /src/GameService/API
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "API.dll"]